line-length = 90
target-version = "py310"

[lint]
# E: pycodestyle errors
# F: Pyflakes
# I: isort
# W: pycodestyle warnings
# C901: McCabe complexity
select = ["E", "F", "I", "W", "C901"]

[lint.mccabe]
max-complexity = 11
